<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
      if(Country::count() <=0 )
      {
          Country::upsert(
              $this->defaultCountries(), 
              uniqueBy:['name', 'code'],
              update:(new Country)->getFillable(),
          );
      }
  }

  /**
   * @var array $countries
   */
  public function defaultCountries()
  {
    return [
      ['name' => 'Afghanistan', 'code' => 'AFG', 'currency_code' => 'AFN'],
      ['name' => 'Albania', 'code' => 'ALB', 'currency_code' => 'ALL'],
      ['name' => 'Algeria', 'code' => 'DZA', 'currency_code' => 'DZD'],
      ['name' => 'Andorra', 'code' => 'AND', 'currency_code' => 'EUR'],
      ['name' => 'Angola', 'code' => 'AGO', 'currency_code' => 'AOA'],
      ['name' => 'Antigua and Barbuda', 'code' => 'ATG', 'currency_code' => 'XCD'],
      ['name' => 'Argentina', 'code' => 'ARG', 'currency_code' => 'ARS'],
      ['name' => 'Armenia', 'code' => 'ARM', 'currency_code' => 'AMD'],
      ['name' => 'Australia', 'code' => 'AUS', 'currency_code' => 'AUD'],
      ['name' => 'Austria', 'code' => 'AUT', 'currency_code' => 'EUR'],
      ['name' => 'Azerbaijan', 'code' => 'AZE', 'currency_code' => 'AZN'],
      ['name' => 'Bahamas', 'code' => 'BHS', 'currency_code' => 'BSD'],
      ['name' => 'Bahrain', 'code' => 'BHR', 'currency_code' => 'BHD'],
      ['name' => 'Bangladesh', 'code' => 'BGD', 'currency_code' => 'BDT'],
      ['name' => 'Barbados', 'code' => 'BRB', 'currency_code' => 'BBD'],
      ['name' => 'Belarus', 'code' => 'BLR', 'currency_code' => 'BYN'],
      ['name' => 'Belgium', 'code' => 'BEL', 'currency_code' => 'EUR'],
      ['name' => 'Belize', 'code' => 'BLZ', 'currency_code' => 'BZD'],
      ['name' => 'Benin', 'code' => 'BEN', 'currency_code' => 'XOF'],
      ['name' => 'Bhutan', 'code' => 'BTN', 'currency_code' => 'BTN'],
      ['name' => 'Bolivia', 'code' => 'BOL', 'currency_code' => 'BOB'],
      ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH', 'currency_code' => 'BAM'],
      ['name' => 'Botswana', 'code' => 'BWA', 'currency_code' => 'BWP'],
      ['name' => 'Brazil', 'code' => 'BRA', 'currency_code' => 'BRL'],
      ['name' => 'Brunei', 'code' => 'BRN', 'currency_code' => 'BND'],
      ['name' => 'Bulgaria', 'code' => 'BGR', 'currency_code' => 'BGN'],
      ['name' => 'Burkina Faso', 'code' => 'BFA', 'currency_code' => 'XOF'],
      ['name' => 'Burundi', 'code' => 'BDI', 'currency_code' => 'BIF'],
      ['name' => 'Cabo Verde', 'code' => 'CPV', 'currency_code' => 'CVE'],
      ['name' => 'Cambodia', 'code' => 'KHM', 'currency_code' => 'KHR'],
      ['name' => 'Cameroon', 'code' => 'CMR', 'currency_code' => 'XAF'],
      ['name' => 'Canada', 'code' => 'CAN', 'currency_code' => 'CAD'],
      ['name' => 'Central African Republic', 'code' => 'CAF', 'currency_code' => 'XAF'],
      ['name' => 'Chad', 'code' => 'TCD', 'currency_code' => 'XAF'],
      ['name' => 'Chile', 'code' => 'CHL', 'currency_code' => 'CLP'],
      ['name' => 'China', 'code' => 'CHN', 'currency_code' => 'CNY'],
      ['name' => 'Colombia', 'code' => 'COL', 'currency_code' => 'COP'],
      ['name' => 'Comoros', 'code' => 'COM', 'currency_code' => 'KMF'],
      ['name' => 'Congo (Congo-Brazzaville)', 'code' => 'COG', 'currency_code' => 'XAF'],
      ['name' => 'Costa Rica', 'code' => 'CRI', 'currency_code' => 'CRC'],
      ['name' => 'Croatia', 'code' => 'HRV', 'currency_code' => 'HRK'],
      ['name' => 'Cuba', 'code' => 'CUB', 'currency_code' => 'CUP'],
      ['name' => 'Cyprus', 'code' => 'CYP', 'currency_code' => 'EUR'],
      ['name' => 'Czechia (Czech Republic)', 'code' => 'CZE', 'currency_code' => 'CZK'],
      ['name' => 'DR Congo (Congo-Kinshasa)', 'code' => 'COD', 'currency_code' => 'CDF'],
      ['name' => 'Denmark', 'code' => 'DNK', 'currency_code' => 'DKK'],
      ['name' => 'Djibouti', 'code' => 'DJI', 'currency_code' => 'DJF'],
      ['name' => 'Dominica', 'code' => 'DMA', 'currency_code' => 'XCD'],
      ['name' => 'Dominican Republic', 'code' => 'DOM', 'currency_code' => 'DOP'],
      ['name' => 'Ecuador', 'code' => 'ECU', 'currency_code' => 'USD'],
      ['name' => 'Egypt', 'code' => 'EGY', 'currency_code' => 'EGP'],
      ['name' => 'El Salvador', 'code' => 'SLV', 'currency_code' => 'USD'],
      ['name' => 'Equatorial Guinea', 'code' => 'GNQ', 'currency_code' => 'XAF'],
      ['name' => 'Eritrea', 'code' => 'ERI', 'currency_code' => 'ERN'],
      ['name' => 'Estonia', 'code' => 'EST', 'currency_code' => 'EUR'],
      ['name' => 'Eswatini (fmr. "Swaziland")', 'code' => 'SWZ', 'currency_code' => 'SZL'],
      ['name' => 'Ethiopia', 'code' => 'ETH', 'currency_code' => 'ETB'],
      ['name' => 'Fiji', 'code' => 'FJI', 'currency_code' => 'FJD'],
      ['name' => 'Finland', 'code' => 'FIN', 'currency_code' => 'EUR'],
      ['name' => 'France', 'code' => 'FRA', 'currency_code' => 'EUR'],
      ['name' => 'Gabon', 'code' => 'GAB', 'currency_code' => 'XAF'],
      ['name' => 'Gambia', 'code' => 'GMB', 'currency_code' => 'GMD'],
      ['name' => 'Georgia', 'code' => 'GEO', 'currency_code' => 'GEL'],
      ['name' => 'Germany', 'code' => 'DEU', 'currency_code' => 'EUR'],
      ['name' => 'Ghana', 'code' => 'GHA', 'currency_code' => 'GHS'],
      ['name' => 'Greece', 'code' => 'GRC', 'currency_code' => 'EUR'],
      ['name' => 'Grenada', 'code' => 'GRD', 'currency_code' => 'XCD'],
      ['name' => 'Guatemala', 'code' => 'GTM', 'currency_code' => 'GTQ'],
      ['name' => 'Guinea', 'code' => 'GIN', 'currency_code' => 'GNF'],
      ['name' => 'Guinea-Bissau', 'code' => 'GNB', 'currency_code' => 'XOF'],
      ['name' => 'Guyana', 'code' => 'GUY', 'currency_code' => 'GYD'],
      ['name' => 'Haiti', 'code' => 'HTI', 'currency_code' => 'HTG'],
      ['name' => 'Holy See', 'code' => 'VAT', 'currency_code' => 'EUR'],
      ['name' => 'Honduras', 'code' => 'HND', 'currency_code' => 'HNL'],
      ['name' => 'Hungary', 'code' => 'HUN', 'currency_code' => 'HUF'],
      ['name' => 'Iceland', 'code' => 'ISL', 'currency_code' => 'ISK'],
      ['name' => 'India', 'code' => 'IND', 'currency_code' => 'INR'],
      ['name' => 'Indonesia', 'code' => 'IDN', 'currency_code' => 'IDR'],
      ['name' => 'Iran', 'code' => 'IRN', 'currency_code' => 'IRR'],
      ['name' => 'Iraq', 'code' => 'IRQ', 'currency_code' => 'IQD'],
      ['name' => 'Ireland', 'code' => 'IRL', 'currency_code' => 'EUR'],
      ['name' => 'Israel', 'code' => 'ISR', 'currency_code' => 'ILS'],
      ['name' => 'Italy', 'code' => 'ITA', 'currency_code' => 'EUR'],
      ['name' => 'Jamaica', 'code' => 'JAM', 'currency_code' => 'JMD'],
      ['name' => 'Japan', 'code' => 'JPN', 'currency_code' => 'JPY'],
      ['name' => 'Jordan', 'code' => 'JOR', 'currency_code' => 'JOD'],
      ['name' => 'Kazakhstan', 'code' => 'KAZ', 'currency_code' => 'KZT'],
      ['name' => 'Kenya', 'code' => 'KEN', 'currency_code' => 'KES'],
      ['name' => 'Kiribati', 'code' => 'KIR', 'currency_code' => 'AUD'],
      ['name' => 'Korea (North)', 'code' => 'PRK', 'currency_code' => 'KPW'],
      ['name' => 'Korea, Republic of (South)', 'code' => 'KOR', 'currency_code' => 'KRW'],
      ['name' => 'Kuwait', 'code' => 'KWT', 'currency_code' => 'KWD'],
      ['name' => 'Kyrgyzstan', 'code' => 'KGZ', 'currency_code' => 'KGS'],
      ['name' => 'Laos', 'code' => 'LAO', 'currency_code' => 'LAK'],
      ['name' => 'Latvia', 'code' => 'LVA', 'currency_code' => 'EUR'],
      ['name' => 'Lebanon', 'code' => 'LBN', 'currency_code' => 'LBP'],
      ['name' => 'Lesotho', 'code' => 'LSO', 'currency_code' => 'LSL'],
      ['name' => 'Liberia', 'code' => 'LBR', 'currency_code' => 'LRD'],
      ['name' => 'Libya', 'code' => 'LBY', 'currency_code' => 'LYD'],
      ['name' => 'Liechtenstein', 'code' => 'LIE', 'currency_code' => 'CHF'],
      ['name' => 'Lithuania', 'code' => 'LTU', 'currency_code' => 'EUR'],
      ['name' => 'Luxembourg', 'code' => 'LUX', 'currency_code' => 'EUR'],
      ['name' => 'Madagascar', 'code' => 'MDG', 'currency_code' => 'MGA'],
      ['name' => 'Malawi', 'code' => 'MWI', 'currency_code' => 'MWK'],
      ['name' => 'Malaysia', 'code' => 'MYS', 'currency_code' => 'MYR'],
      ['name' => 'Maldives', 'code' => 'MDV', 'currency_code' => 'MVR'],
      ['name' => 'Mali', 'code' => 'MLI', 'currency_code' => 'XOF'],
      ['name' => 'Malta', 'code' => 'MLT', 'currency_code' => 'EUR'],
      ['name' => 'Marshall Islands', 'code' => 'MHL', 'currency_code' => 'USD'],
      ['name' => 'Mauritania', 'code' => 'MRT', 'currency_code' => 'MRU'],
      ['name' => 'Mauritius', 'code' => 'MUS', 'currency_code' => 'MUR'],
      ['name' => 'Mexico', 'code' => 'MEX', 'currency_code' => 'MXN'],
      ['name' => 'Micronesia', 'code' => 'FSM', 'currency_code' => 'USD'],
      ['name' => 'Moldova', 'code' => 'MDA', 'currency_code' => 'MDL'],
      ['name' => 'Monaco', 'code' => 'MCO', 'currency_code' => 'EUR'],
      ['name' => 'Mongolia', 'code' => 'MNG', 'currency_code' => 'MNT'],
      ['name' => 'Montenegro', 'code' => 'MNE', 'currency_code' => 'EUR'],
      ['name' => 'Morocco', 'code' => 'MAR', 'currency_code' => 'MAD'],
      ['name' => 'Mozambique', 'code' => 'MOZ', 'currency_code' => 'MZN'],
      ['name' => 'Myanmar (formerly Burma)', 'code' => 'MMR', 'currency_code' => 'MMK'],
      ['name' => 'Namibia', 'code' => 'NAM', 'currency_code' => 'NAD'],
      ['name' => 'Nauru', 'code' => 'NRU', 'currency_code' => 'AUD'],
      ['name' => 'Nepal', 'code' => 'NPL', 'currency_code' => 'NPR'],
      ['name' => 'Netherlands', 'code' => 'NLD', 'currency_code' => 'EUR'],
      ['name' => 'New Zealand', 'code' => 'NZL', 'currency_code' => 'NZD'],
      ['name' => 'Nicaragua', 'code' => 'NIC', 'currency_code' => 'NIO'],
      ['name' => 'Niger', 'code' => 'NER', 'currency_code' => 'XOF'],
      ['name' => 'Nigeria', 'code' => 'NGA', 'currency_code' => 'NGN'],
      ['name' => 'North Korea', 'code' => 'PRK', 'currency_code' => 'KPW'],
      ['name' => 'North Macedonia (formerly Macedonia)', 'code' => 'MKD', 'currency_code' => 'MKD'],
      ['name' => 'Norway', 'code' => 'NOR', 'currency_code' => 'NOK'],
      ['name' => 'Oman', 'code' => 'OMN', 'currency_code' => 'OMR'],
      ['name' => 'Pakistan', 'code' => 'PAK', 'currency_code' => 'PKR'],
      ['name' => 'Palau', 'code' => 'PLW', 'currency_code' => 'USD'],
      ['name' => 'Palestine State', 'code' => 'PSE', 'currency_code' => 'ILS'],
      ['name' => 'Panama', 'code' => 'PAN', 'currency_code' => 'PAB'],
      ['name' => 'Papua New Guinea', 'code' => 'PNG', 'currency_code' => 'PGK'],
      ['name' => 'Paraguay', 'code' => 'PRY', 'currency_code' => 'PYG'],
      ['name' => 'Peru', 'code' => 'PER', 'currency_code' => 'PEN'],
      ['name' => 'Philippines', 'code' => 'PHL', 'currency_code' => 'PHP'],
      ['name' => 'Poland', 'code' => 'POL', 'currency_code' => 'PLN'],
      ['name' => 'Portugal', 'code' => 'PRT', 'currency_code' => 'EUR'],
      ['name' => 'Qatar', 'code' => 'QAT', 'currency_code' => 'QAR'],
      ['name' => 'Romania', 'code' => 'ROU', 'currency_code' => 'RON'],
      ['name' => 'Russia', 'code' => 'RUS', 'currency_code' => 'RUB'],
      ['name' => 'Rwanda', 'code' => 'RWA', 'currency_code' => 'RWF'],
      ['name' => 'Saint Kitts and Nevis', 'code' => 'KNA', 'currency_code' => 'XCD'],
      ['name' => 'Saint Lucia', 'code' => 'LCA', 'currency_code' => 'XCD'],
      ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VCT', 'currency_code' => 'XCD'],
      ['name' => 'Samoa', 'code' => 'WSM', 'currency_code' => 'WST'],
      ['name' => 'San Marino', 'code' => 'SMR', 'currency_code' => 'EUR'],
      ['name' => 'Sao Tome and Principe', 'code' => 'STP', 'currency_code' => 'STN'],
      ['name' => 'Saudi Arabia', 'code' => 'SAU', 'currency_code' => 'SAR'],
      ['name' => 'Senegal', 'code' => 'SEN', 'currency_code' => 'XOF'],
      ['name' => 'Serbia', 'code' => 'SRB', 'currency_code' => 'RSD'],
      ['name' => 'Seychelles', 'code' => 'SYC', 'currency_code' => 'SCR'],
      ['name' => 'Sierra Leone', 'code' => 'SLE', 'currency_code' => 'SLL'],
      ['name' => 'Singapore', 'code' => 'SGP', 'currency_code' => 'SGD'],
      ['name' => 'Slovakia', 'code' => 'SVK', 'currency_code' => 'EUR'],
      ['name' => 'Slovenia', 'code' => 'SVN', 'currency_code' => 'EUR'],
      ['name' => 'Solomon Islands', 'code' => 'SLB', 'currency_code' => 'SBD'],
      ['name' => 'Somalia', 'code' => 'SOM', 'currency_code' => 'SOS'],
      ['name' => 'South Africa', 'code' => 'ZAF', 'currency_code' => 'ZAR'],
      ['name' => 'South Sudan', 'code' => 'SSD', 'currency_code' => 'SSP'],
      ['name' => 'Spain', 'code' => 'ESP', 'currency_code' => 'EUR'],
      ['name' => 'Sri Lanka', 'code' => 'LKA', 'currency_code' => 'LKR'],
      ['name' => 'Sudan', 'code' => 'SDN', 'currency_code' => 'SDG'],
      ['name' => 'Suriname', 'code' => 'SUR', 'currency_code' => 'SRD'],
      ['name' => 'Sweden', 'code' => 'SWE', 'currency_code' => 'SEK'],
      ['name' => 'Switzerland', 'code' => 'CHE', 'currency_code' => 'CHF'],
      ['name' => 'Syria', 'code' => 'SYR', 'currency_code' => 'SYP'],
      ['name' => 'Taiwan', 'code' => 'TWN', 'currency_code' => 'TWD'],
      ['name' => 'Tajikistan', 'code' => 'TJK', 'currency_code' => 'TJS'],
      ['name' => 'Tanzania', 'code' => 'TZA', 'currency_code' => 'TZS'],
      ['name' => 'Thailand', 'code' => 'THA', 'currency_code' => 'THB'],
      ['name' => 'Timor-Leste', 'code' => 'TLS', 'currency_code' => 'USD'],
      ['name' => 'Togo', 'code' => 'TGO', 'currency_code' => 'XOF'],
      ['name' => 'Tonga', 'code' => 'TON', 'currency_code' => 'TOP'],
      ['name' => 'Trinidad and Tobago', 'code' => 'TTO', 'currency_code' => 'TTD'],
      ['name' => 'Tunisia', 'code' => 'TUN', 'currency_code' => 'TND'],
      ['name' => 'Turkey', 'code' => 'TUR', 'currency_code' => 'TRY'],
      ['name' => 'Turkmenistan', 'code' => 'TKM', 'currency_code' => 'TMT'],
      ['name' => 'Tuvalu', 'code' => 'TUV', 'currency_code' => 'AUD'],
      ['name' => 'Uganda', 'code' => 'UGA', 'currency_code' => 'UGX'],
      ['name' => 'Ukraine', 'code' => 'UKR', 'currency_code' => 'UAH'],
      ['name' => 'United Arab Emirates', 'code' => 'ARE', 'currency_code' => 'AED'],
      ['name' => 'United Kingdom', 'code' => 'GBR', 'currency_code' => 'GBP'],
      ['name' => 'United States', 'code' => 'USA', 'currency_code' => 'USD'],
      ['name' => 'Uruguay', 'code' => 'URY', 'currency_code' => 'UYU'],
      ['name' => 'Uzbekistan', 'code' => 'UZB', 'currency_code' => 'UZS'],
      ['name' => 'Vanuatu', 'code' => 'VUT', 'currency_code' => 'VUV'],
      ['name' => 'Venezuela', 'code' => 'VEN', 'currency_code' => 'VES'],
      ['name' => 'Vietnam', 'code' => 'VNM', 'currency_code' => 'VND'],
      ['name' => 'Yemen', 'code' => 'YEM', 'currency_code' => 'YER'],
      ['name' => 'Zambia', 'code' => 'ZMB', 'currency_code' => 'ZMW'],
      ['name' => 'Zimbabwe', 'code' => 'ZWE', 'currency_code' => 'ZWL']
    ];
  }
    
}
